### ISSUE TITLE
Swift 2.0 link error

### ISSUE THREAD

**Issue by claudiuvintila** [desktopadsdk/DesktopAD-SDK-For-OSX#2]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_WebView", referenced from:
      _OBJC_CLASS_$_DAWebview in DesktopADlib.a(DAWebview.o)
  "_OBJC_METACLASS_$_WebView", referenced from:
      _OBJC_METACLASS_$_DAWebview in DesktopADlib.a(DAWebview.o)
  "_WebActionNavigationTypeKey", referenced from:
      -[DesktopAdWebview webView:decidePolicyForNavigationAction:request:frame:decisionListener:] in DesktopADlib.a(DesktopAdWebview.o)
      -[DesktopAdWebview webView:decidePolicyForNewWindowAction:request:newFrameName:decisionListener:] in DesktopADlib.a(DesktopAdWebview.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Environment:
MacBook Pro with OSX 10.11
Xcode 7.1
Swift 2.0

**Comment by ContactDesktopAd** [comment]
Would you please check whether you have added this as attachment showing?
![add this](https://cloud.githubusercontent.com/assets/12893316/10899138/b5c630ce-820c-11e5-86bb-f5fce418b937.jpg)

**Comment by claudiuvintila** [comment]
That fixed it. Thank you!
